stages:
  - test
  - publish

variables:
  DOCKER_HOST: tcp://pio-gitlab-runner-components-dind.gitlab-runner-components.svc.cluster.local:2375
  DOCKER_TLS_CERTDIR: ""
  PIO_TAG: ${CI_COMMIT_REF_SLUG}

.base:
  image: python:3.6.8-stretch
  tags: ["kube", "bel1-c2"]

test-lint:
  stage: test
  extends: .base
  script:
    - pip install pycodestyle pyflakes
    - pycodestyle --config pep8lint.cfg --statistics --format=pylint *.py previsionio/*.py utests/*.py
    - pyflakes  *.py previsionio/*.py utests/*.py
  allow_failure: true

test-image:
  stage: test
  extends: .base
  interruptible: true
  script:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install -r utests/requirements.txt
    - cd utests/
    - pytest -sv test_exporters.py
  timeout: 3h
  allow_failure: true

build:
  stage: publish
  extends: .base
  script:
    - pip install versioneer twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url $PYPI_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - curl -L --output /usr/local/bin/release-cli "https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-linux-amd64"; chmod +x /usr/local/bin/release-cli
  only:
    - tags
  release:
    tag_name: $CI_COMMIT_TAG
    description: "new version"

test-publish:
  stage: publish
  extends: .base
  script:
    - pip install previsionio
  only:
    - tags
