stages:
  - test

variables:
  DOCKER_HOST: tcp://pio-gitlab-runner-components-dind.gitlab-runner-components.svc.cluster.local:2375
  DOCKER_TLS_CERTDIR: ""
  PIO_TAG: ${CI_COMMIT_REF_SLUG}

.base:
  image: python:3.6.8-slim-stretch
  tags: ["kube", "bel1-c2"]

test-lint:
  stage: test
  extends: .base
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install --no-cache-dir -r utests/requirements.txt
    - pycodestyle --config pep8lint.cfg --statistics --format=pylint *.py previsionio/*.py utests/*.py
    - pyflakes  *.py previsionio/*.py utests/*.py

test-image:
  stage: test
  extends: .base
  interruptible: true
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install --no-cache-dir -r utests/requirements.txt
    - pytest utests/
  timeout: 3h
