stages:
  - sync
  - test

variables:
  DOCKER_HOST: tcp://pio-gitlab-runner-components-dind.gitlab-runner-components.svc.cluster.local:2375
  DOCKER_TLS_CERTDIR: ""
  PIO_TAG: ${CI_COMMIT_REF_SLUG}

.base:
  image: python:3.6.8-slim-stretch
  tags: ["kube", "bel1-c2"]

synchro:
  stage: sync
  extends: .base
  image: $PREVISION_REGISTRY_ADDR/prevision/docker:19.03.1
  script:
    - git pull https://github.com/previsionio/prevision-python.git
    - git push

test-lint:
  stage: test
  extends: .base
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install --no-cache-dir -r utests/requirements.txt
    - pycodestyle --config pep8lint.cfg --statistics --format=pylint *.py previsionio/*.py utests/*.py
    - pyflakes  *.py previsionio/*.py utests/*.py
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

test-image:
  stage: test
  extends: .base
  interruptible: true
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pip install --no-cache-dir -r utests/requirements.txt
    - pytest utests/
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
